name: Flask CI/CD

on:
  push:
    branches:
      - master   # deploy on push to master

jobs:
  build-test-deploy:
    runs-on: ubuntu-latest

    steps:
    - name: Checkout code
      uses: actions/checkout@v4

    # - name: Set up Python
    #   uses: actions/setup-python@v5
    #   with:
    #     python-version: '3.10'

    # - name: Install dependencies
    #   run: |
    #     python -m pip install --upgrade pip
    #     pip install -r requirements.txt

    # - name: Run tests
    #   run: pytest

    - name: Deploy to Ubuntu Server
      env:
        HOST: ${{ secrets.SSH_HOST }}
        USER: ${{ secrets.SSH_USER }}
        PRIVATE_KEY: ${{ secrets.SSH_KEY }}
      run: |
        echo "$PRIVATE_KEY" > private_key.pem
        chmod 600 private_key.pem
        ssh -i private_key.pem -o StrictHostKeyChecking=no $USER@$HOST "
          cd /home/esp32ota-backend &&
          git pull origin master &&
          source env/bin/activate &&
          pip install -r requirements.txt &&
          sudo systemctl restart esp32-ota.service
        "
